name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
      with:
        repository: caravel-io/caravel
        ref: refs/heads/develop
    - name: Build
      run: cd caravel_test_module; cargo build --verbose --release
    - name: Upload release artifact
      uses: actions/upload-artifact@v4
      with:
        name: libFile.so
        path: caravel_test_module/target/release/libFile.so
